language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk8

# skip the implicit install step
install: true

script:
  - make javadoc
  - make build-travis
  - make travis-e2e-use-case

#deploy:
#  provider: script
#  script: make build-travis && ./mvnw -s ./.travis/settings.xml clean deploy
after_success:
  - ./.travis/.travis.release.jars.sh

cache:
  directories:
  - $HOME/.m2
